version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: web_dashboard
    environment:
      DB_HOST: postgres
      DB_PORT: 5434
      DB_NAME: mydb
      DB_USER: admin
      DB_PASSWORD: admin123
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
